//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProjesi_4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Bilgiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bilgiler()
        {
            this.Bilgiler1 = new HashSet<Bilgiler>();
        }   
        public int ID { get; set; }
        [Required(ErrorMessage = "Boş bırakmayınız")]
        public string AD { get; set; }
        [Required(ErrorMessage = "Boş bırakmayınız")]
        public string SOYAD { get; set; }
        [Range(1000000000, 9999999999, ErrorMessage = "Telefon 11 karakterden oluşmaldır!")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Boş bırakmayınız")]
        public string TELEFON { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public Nullable<int> YNTBİLGİ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilgiler> Bilgiler1 { get; set; }
        public virtual Bilgiler Bilgiler2 { get; set; }
        public virtual Departman Departman1 { get; set; }
    }
}
